#!/usr/bin/env python3

import medusa as m
import sys
import argparse

def validate(args):
    for f in args.FILE:
        print(f'Dataset "{f}":\t{"ok" if m.validate(f) else "FAILED"}')

if __name__ == "__main__":
    p = argparse.ArgumentParser(description='Manage Medusa data sets')
    ps = p.add_subparsers()
    val = ps.add_parser('validate', description='Validate a data set')
    val.add_argument('FILE', nargs='+', help='data set directory.')
    val.set_defaults(func = validate)
    args = p.parse_args()
    args.func(args)
    



